name = "scala_stdlib"
version = "0.0.1"
licences = ["AGPL-3.0-or-later"]
description = "An extended standard library for the Gleam programming language inspired by Scala language and its ecosystem"

repository = { type = "github", user = "varcorsd", repo = "scala-stdlib-4-gleam" }

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"
